# Generated by Django 3.1.5 on 2021-01-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_form',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
