# Generated by Django 3.1.5 on 2021-01-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('phone_num', models.IntegerField(max_length=11)),
                ('major', models.CharField(max_length=15)),
            ],
        ),
    ]
